### ISSUE TITLE
Seek for contact

### ISSUE THREAD

**Issue by PaulAlist** [wimdeblauwe/ttcli#110]
Mr. Deblauwe, sorry to wtite here but I cannot find any other way to contact you. My name is Pavel, I'm an editor at the publishing house in Republic of Kazakhstan. We are interested in translating your book "Modern frontends with htmx", is the translation rights for this book available? If yes, please contact me at alist.publishing@gmail.com. Thank you!

**Comment by wimdeblauwe** [comment]
I have contacted you via email.
