### ISSUE TITLE
Syntax error in closing comment (HTML)

### ISSUE THREAD

**Issue by jsrois** [wimdeblauwe/ttcli#118]
I think there is an extra `-` at the end of this comment, shouldn't it be `-->`? 

https://github.com/wimdeblauwe/ttcli/blob/c7fba72e838087fe6e8a81c79e659abd7cb8af4c/src/main/resources/files/templates/index.html#L13

Regards

**Comment by wimdeblauwe** [comment]
Indeed! Thanks for reporting.
