### ISSUE TITLE
Add Spring Boot DevTools as a live reload option

### ISSUE THREAD

**Issue by wimdeblauwe** [wimdeblauwe/ttcli#143]
For people that don't like to use npm, we can add a Spring Boot DevTools based version for the live reload setup. For use with Tailwind CSS, we can take inspiration from https://github.com/danvega/spring-boot-tailwind and https://maciejwalkowiak.com/blog/spring-boot-thymeleaf-tailwindcss/

**Comment by PremJyoti** [comment]
You can add the below for spring boot dev tools, dependency in your pom.xml

<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>

**Comment by PremJyoti** [comment]
You can add the below for spring boot dev tools, dependency in your pom.xml 

<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>

**Comment by PremJyoti** [comment]
You can add the spring boot dev tools dependency in your pom.
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
