### ISSUE TITLE
npm build-prod error (windows 10, cmd.exe)

### ISSUE THREAD

**Issue by ghost** [wimdeblauwe/ttcli#147]
windows 10, cmd.exe

d:\taming-thymeleaf>npm run build-prod

> build-prod
> NODE_ENV='production' npm-run-all --parallel build-prod:*

'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.

**Comment by wimdeblauwe** [comment]
I don't have windows, but maybe https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows can help you fix it ?

**Comment by wimdeblauwe** [comment]
Closing this issue as no feedback has been provided.
