### ISSUE TITLE
ttcli init fails for npm-based-with-tailwind-css - Using `node@v21.6.1` with `npm@10.2.4`

### ISSUE THREAD

**Issue by selop** [wimdeblauwe/ttcli#156]
<img width="1064" alt="Screenshot 2024-09-22 at 14 58 20" src="https://github.com/user-attachments/assets/3ad97eea-a6e0-474d-98d6-d115eda667c3">

the `ttcli init` command fails with a RunTimeException `unable to init tailwind css`:
<img width="1688" alt="Screenshot 2024-09-22 at 14 57 06" src="https://github.com/user-attachments/assets/5194e000-8248-4524-aa90-420f4bdf527c">

The JDK I am using is :
<img width="1539" alt="Screenshot 2024-09-22 at 15 06 18" src="https://github.com/user-attachments/assets/a65deb1f-586a-4f5d-aae7-22564199c975">

**Comment by wimdeblauwe** [comment]
Is there more information in the log file that is generated?

**Comment by wimdeblauwe** [comment]
I managed to reproduce the problem on my macOS using `node v22.9.0 (npm v10.8.3)`. When I use the latest LTS version, it works (`node v20.17.0 (npm v10.8.2)`).

**Comment by selop** [comment]
Thanks for the quick update. I've switched down to `node v20.17.0 with npm 10.8.2` and it works for me as well. 👍  
I could not see any additional output. Browsing in `NpmBasedLiveReloadInitSerivce` I could not see anything evident w/o digging deeper into the code.
