### ISSUE TITLE
Tailwind not installed, npm overwrites files

### ISSUE THREAD

**Issue by LiveNathan** [wimdeblauwe/ttcli#20]
Hey Wim, I'm following along in your book, setting up a new test project. After ttcli init, editing the index.html, and running npm run build && npm run watch, I cannot see any Tailwind CSS styling and somehow, magically, my index file is overwritten with the original HTML from the project init.

**Comment by wimdeblauwe** [comment]
That is strange. You did enable the Tailwind support when running the tool? What is the exact path of the index.html file you changed?

**Comment by LiveNathan** [comment]
Hey Wim, yes, following the steps in your book. I just re-ran the test and was not able to recreate the issue. False alarm! ¯\_(ツ)_/¯
