### ISSUE TITLE
segfault when running ttcli init on Windows 11

### ISSUE THREAD

**Issue by JJ139** [wimdeblauwe/ttcli#21]
[ttcli.log](https://github.com/wimdeblauwe/ttcli/files/11191780/ttcli.log)

**Comment by wimdeblauwe** [comment]
Stacktrace shows this:

```
java.lang.NullPointerException: null
	at java.base@17.0.6/sun.net.dns.ResolverConfigurationImpl.stringToList(ResolverConfigurationImpl.java:69) ~[na:na]
	at java.base@17.0.6/sun.net.dns.ResolverConfigurationImpl.loadConfig(ResolverConfigurationImpl.java:136) ~[na:na]
	at java.base@17.0.6/sun.net.dns.ResolverConfigurationImpl.nameservers(ResolverConfigurationImpl.java:159) ~[na:na]
	at jdk.naming.dns@17.0.6/com.sun.jndi.dns.DnsContextFactory.serversForUrls(DnsContextFactory.java:149) ~[ttcli.exe:na]
	at jdk.naming.dns@17.0.6/com.sun.jndi.dns.DnsContextFactory.getContext(DnsContextFactory.java:81) ~[ttcli.exe:na]
```

Just a wild guess, but is there any special DNS configuration on this computer?

**Comment by JJ139** [comment]
I don't think so. Have tried some suggested fixes but none working so far. I'll try following along your book using a manual setup instead.

**Comment by wimdeblauwe** [comment]
Ok, did you manage to do a manual setup? Otherwise, you could run the Java version instead of the native version. I do see I don't publish those, so you would have to first compile it yourself. Would be interesting to see if the same NPE also appears when running on the JVM.

**Comment by JJ139** [comment]
Hi Wim, when running the java version, the option menu does not appear after running the 'init' command. Instead the following error is thrown: Context does not contain key: group-id.

**Comment by wimdeblauwe** [comment]
Could you try again with the latest version 0.8.0? You can now download the jar file to run it from the release page: https://github.com/wimdeblauwe/ttcli/releases/tag/0.8.0

I probably won't change anything, but I would like to be sure.

**Comment by wigglebabo** [comment]
Log file when running on Windows 11 using native build of 0.8.0: 
[ttcli.log](https://github.com/wimdeblauwe/ttcli/files/11415180/ttcli.log)

**Comment by wimdeblauwe** [comment]
Version 0.9.0 should now fix this. Could you please test to confirm @JJ139 ?

**Comment by wimdeblauwe** [comment]
The Java build is now ok on Windows, but the native executable still fails due to GraalVM issue https://github.com/oracle/graal/issues/4304

**Comment by wimdeblauwe** [comment]
Workaround implemented. Version https://github.com/wimdeblauwe/ttcli/releases/tag/0.9.3 now fully works on Windows.
