### ISSUE TITLE
Warn if minimum node version is not available

### ISSUE THREAD

**Issue by linus1412** [wimdeblauwe/ttcli#42]
Steps to recreate

brew install wimdeblauwe/homebrew-ttcli/ttcli

This installed version 0.10.1

ttcli init                                     

? Group:  com.example
? Artifact:  demo
? Project Name:  Demo
? Select Spring Boot version 3.1.0.RELEASE
? Select live reload implementation: npm-based-with-tailwind-css
? Web dependencies htmx
🍃 Generating Spring Boot project
🛠️  Using node v12.22.1 with npm 6.14.12
🔨 Installing npm dependencies
👷‍♂️ Adding npm build scripts
👷🏻‍♀️ Updating Maven pom.xml

> unable to init tailwind css
> java.lang.RuntimeException: unable to init tailwind css
> 	at io.github.wimdeblauwe.ttcli.livereload.npm.NpmBasedWithTailwindCssLiveReloadInitService.initializeTailwindConfig(NpmBasedWithTailwindCssLiveReloadInitService.java:118)
> 	at io.github.wimdeblauwe.ttcli.livereload.npm.NpmBasedWithTailwindCssLiveReloadInitService.setupTailwindConfig(NpmBasedWithTailwindCssLiveReloadInitService.java:103)
> 	at io.github.wimdeblauwe.ttcli.livereload.npm.NpmBasedWithTailwindCssLiveReloadInitService.generate(NpmBasedWithTailwindCssLiveReloadInitService.java:60)
> 	at io.github.wimdeblauwe.ttcli.ProjectInitializationService.initialize(ProjectInitializationService.java:54)
> 	at io.github.wimdeblauwe.ttcli.Init.init(Init.java:62)
> 	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
> 	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
> 	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:222)
> 	at org.springframework.shell.Shell.evaluate(Shell.java:246)
> 	at org.springframework.shell.Shell.run(Shell.java:158)
> 	at org.springframework.shell.jline.NonInteractiveShellRunner.run(NonInteractiveShellRunner.java:129)
> 	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760)
> 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
> 	at io.github.wimdeblauwe.ttcli.TamingThymeleafCliApplication.main(TamingThymeleafCliApplication.java:10)

Just because I did, after the failure I tried running 

cd demo
./mvnw test

(I had to chmod +x ./mvnw first)

./mvnw test    

> [INFO] Scanning for projects...
> [INFO] 
> [INFO] --------------------------< com.example:demo >--------------------------
> [INFO] Building Demo 0.0.1-SNAPSHOT
> [INFO]   from pom.xml
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- frontend:1.12.1:install-node-and-npm (install-frontend-tooling) @ demo ---
> [INFO] Installing node version v12.22.1
> [INFO] Unpacking /Users/martins/.m2/repository/com/github/eirslett/node/12.22.1/node-12.22.1-darwin-x64.tar.gz into /Users/martins/demo/node/tmp
> [INFO] Copying node binary from /Users/martins/demo/node/tmp/node-v12.22.1-darwin-x64/bin/node to /Users/martins/demo/node/node
> [INFO] Installed node locally.

> [INFO] Installing npm version 6.14.12
> [INFO] Unpacking /Users/martins/.m2/repository/com/github/eirslett/npm/6.14.12/npm-6.14.12.tar.gz into /Users/martins/demo/node/node_modules
> [INFO] Installed npm locally.
> [INFO] 
> [INFO] --- frontend:1.12.1:npm (run-npm-install) @ demo ---
> [INFO] Running 'npm install' in /Users/martins/demo
> [INFO] npm WARN @babel/cli@7.21.5 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
> [INFO] npm WARN demo@ No description
> [INFO] npm WARN demo@ No repository field.
> [INFO] npm WARN demo@ No license field.
> [INFO] 
> [INFO] audited 466 packages in 1.81s
> [INFO] 
> [INFO] 107 packages are looking for funding
> [INFO]   run `npm fund` for details
> [INFO] 
> [INFO] found 0 vulnerabilities
> [INFO] 
> [INFO] 
> [INFO] --- frontend:1.12.1:npm (run-npm-build) @ demo ---
> [INFO] Running 'npm run build' in /Users/martins/demo
> [INFO] 
> [INFO] > demo@ build /Users/martins/demo
> [INFO] > npm-run-all --parallel build:*
> [INFO] 
> [INFO] 
> [INFO] > demo@ build:html /Users/martins/demo
> [INFO] > recursive-copy "src/main/resources/templates" target/classes/templates -w
> [INFO] 
> [INFO] 
> [INFO] > demo@ build:css /Users/martins/demo
> [INFO] > mkdirp target/classes/static/css && postcss src/main/resources/static/css/*.css -d target/classes/static/css
> [INFO] 
> [INFO] 
> [INFO] > demo@ build:svg /Users/martins/demo
> [INFO] > path-exists src/main/resources/static/svg && recursive-copy "src/main/resources/static/svg" target/classes/static/svg -w -f "**/*.svg" || echo "No 'src/main/resources/static/svg' directory found."
> [INFO] 
> [INFO] 
> [INFO] > demo@ build:js /Users/martins/demo
> [INFO] > path-exists src/main/resources/static/js && (mkdirp target/classes/static/js && babel src/main/resources/static/js/ --out-dir target/classes/static/js/) || echo "No 'src/main/resources/static/js' directory found."
> [INFO] 
> [INFO] src/main/resources/templates -> target/classes/templates
> [INFO] 1 item(s) copied
> [INFO] No 'src/main/resources/static/svg' directory found.
> [INFO] No 'src/main/resources/static/js' directory found.
> [INFO] /Users/martins/demo/node_modules/yaml/dist/compose/composer.js:33
> [INFO]                 **if (prelude[i + 1]?.[0] !== '#')**
> [INFO]                                    ^
> [INFO] 
> [INFO] SyntaxError: Unexpected token '.'
> [INFO]     at wrapSafe (internal/modules/cjs/loader.js:915:16)
> [INFO]     at Module._compile (internal/modules/cjs/loader.js:963:27)
> [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> [INFO]     at Module.load (internal/modules/cjs/loader.js:863:32)
> [INFO]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> [INFO]     at Module.require (internal/modules/cjs/loader.js:887:19)
> [INFO]     at require (internal/modules/cjs/helpers.js:74:18)
> [INFO]     at Object.<anonymous> (/Users/martins/demo/node_modules/yaml/dist/index.js:3:16)
> [INFO]     at Module._compile (internal/modules/cjs/loader.js:999:30)
> [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> [INFO] npm ERR! code ELIFECYCLE
> [INFO] npm ERR! errno 1
> [INFO] npm ERR! demo@ build:css: `mkdirp target/classes/static/css && postcss src/main/resources/static/css/*.css -d target/classes/static/css`
> [INFO] npm ERR! Exit status 1
> [INFO] npm ERR! 
> [INFO] npm ERR! Failed at the demo@ build:css script.
> [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [INFO] 
> [INFO] npm ERR! A complete log of this run can be found in:
> [INFO] npm ERR!     /Users/martins/.npm/_logs/2023-06-06T12_27_49_765Z-debug.log
> [INFO] ERROR: "build:css" exited with 1.
> [INFO] npm ERR! code ELIFECYCLE
> [INFO] npm ERR! errno 1
> [INFO] npm ERR! demo@ build: `npm-run-all --parallel build:*`
> [INFO] npm ERR! Exit status 1
> [INFO] npm ERR! 
> [INFO] npm ERR! Failed at the demo@ build script.
> [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [INFO] 
> [INFO] npm ERR! A complete log of this run can be found in:
> [INFO] npm ERR!     /Users/martins/.npm/_logs/2023-06-06T12_27_49_813Z-debug.log
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  9.931 s
> [INFO] Finished at: 2023-06-06T13:27:49+01:00
> [INFO] ------------------------------------------------------------------------
> [WARNING] 
> [WARNING] Plugin validation issues were detected in 1 plugin(s)
> [WARNING] 
> [WARNING]  * com.github.eirslett:frontend-maven-plugin:1.12.1
> [WARNING] 
> [WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
> [WARNING] 
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (run-npm-build) on project demo: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

The interesting bit of which seems to be

> [INFO] src/main/resources/templates -> target/classes/templates
> [INFO] 1 item(s) copied
> [INFO] No 'src/main/resources/static/svg' directory found.
> [INFO] No 'src/main/resources/static/js' directory found.
> [INFO] /Users/martins/demo/node_modules/yaml/dist/compose/composer.js:33
> [INFO]                 **if (prelude[i + 1]?.[0] !== '#')**
> [INFO] 
> [INFO] SyntaxError: Unexpected token '.'
> [INFO]     at wrapSafe (internal/modules/cjs/loader.js:915:16)
> [INFO]     at Module._compile (internal/modules/cjs/loader.js:963:27)
> [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> [INFO]     at Module.load (internal/modules/cjs/loader.js:863:32)
> [INFO]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> [INFO]     at Module.require (internal/modules/cjs/loader.js:887:19)
> [INFO]     at require (internal/modules/cjs/helpers.js:74:18)
> [INFO]     at Object.<anonymous> (/Users/martins/demo/node_modules/yaml/dist/index.js:3:16)
> [INFO]     at Module._compile (internal/modules/cjs/loader.js:999:30)
> [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by linus1412** [comment]
I'm guessing that it is something to do with this issue

https://github.com/tailwindlabs/tailwindcss/discussions/8807#discussioncomment-5924693

**Comment by linus1412** [comment]
I've got past this.

The problem was that ttcli installed tailwindcss 3.3.2 which requires node version > 12 and i was using 12.  Switching my node version to 14 has resolved this issue.

Perhaps the README could be updated to reflect a minimum node version?

**Comment by wimdeblauwe** [comment]
Thank you for figuring out what was wrong exactly. I'll add a version check to avoid this in the future in an upcoming version.
