### ISSUE TITLE
Tailwind not working

### ISSUE THREAD

**Issue by LiveNathan** [wimdeblauwe/ttcli#73]
Hey Wim, I just installed a new project to test and it seem like Tailwind is not working. 

Upgraded to 0.14
<img width="291" alt="2023-10-06 at 18 18 30@2x" src="https://github.com/wimdeblauwe/ttcli/assets/60303904/c476a3c5-db8b-4e00-8108-0ba2fee87a0d">

init
<img width="696" alt="2023-10-06 at 18 19 41@2x" src="https://github.com/wimdeblauwe/ttcli/assets/60303904/06891bff-7ec0-433a-b533-4bd9a61cb297">

run build
<img width="1091" alt="2023-10-06 at 18 20 20@2x" src="https://github.com/wimdeblauwe/ttcli/assets/60303904/3a1ff0a6-b471-410d-bccf-a8e5345b45a3">

**Comment by LiveNathan** [comment]
I made no changes to Tailwind.config
<img width="536" alt="2023-10-06 at 18 21 46@2x" src="https://github.com/wimdeblauwe/ttcli/assets/60303904/15d98526-ad24-4cd2-ae08-c6aaaf5f252b">

**Comment by LiveNathan** [comment]
I have used ttcli several times before without issue. Not sure what's going on now.

**Comment by LiveNathan** [comment]
Hmmm, interesting. It works in an incognito window.
![2023-10-06 at 18 23 10](https://github.com/wimdeblauwe/ttcli/assets/60303904/fa3aafa5-187a-4cd8-94e6-ba0f2430dc09)

**Comment by LiveNathan** [comment]
Ok, now it's working in my other project as well. Damn. I don't know what was going on. Ok, never mind! :)

**Comment by wimdeblauwe** [comment]
That is very weird indeed. Glad you got it working in the end.
