### ISSUE TITLE
alpinejs version is set to 3.13.2 but doesn't exist

### ISSUE THREAD

**Issue by maxwellt** [wimdeblauwe/ttcli#80]
Hi Wim

When using ttcli it generates the pom that uses version 3.13.2 for the AlphineJS webjar version but [Maven Central](https://central.sonatype.com/artifact/org.webjars.npm/alpinejs/versions) has 3.13.1 as its latest version.

**Comment by wimdeblauwe** [comment]
Thank you for letting me know. I am generating the version now (Via https://www.webjars.org/). It should be available in a few hours. You can manually use 3.13.1 in the `pom.xml` for now until it is available.

**Comment by wimdeblauwe** [comment]
Version is now available.
