### ISSUE TITLE
ttcli 1.1.0 broken on apple silicon

### ISSUE THREAD

**Issue by mmonge** [wimdeblauwe/ttcli#92]
Hello Wim,

Thank you very much for this fantastic tool. I discovered it a week ago, but today it got broken for me.

I'm using an Apple Silicon; I know it has no support. However, version 1.0.0 worked fine with Rosetta2.

Version 1.1.0 gave me this error:

```
❯ ttcli help
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.
```

I rolled back to version 1.0.0, and it works fine again:

```
# Steps to install 1.0.0 with Homebrew:

❯ brew uninstall ttcli

❯ brew tap-new $USER/local-ttcli

❯ brew extract --version=1.0.0 wimdeblauwe/homebrew-ttcli/ttcli $USER/local-ttcli

❯ brew install ttcli@1.0.0
```

I found this spring boot issue that looks like the same error message. Maybe you can give it a look:

[/spring-projects/spring-boot/issues/36576#issuecomment-1651093475](https://github.com/spring-projects/spring-boot/issues/36576#issuecomment-1651093475)

Please let me know if you need my help to test it on Apple Silicon; if you are too busy to check it, let me know to find some time next week. I can configure a forked repo to build it on GitHub.

**Comment by merikan** [comment]
Read the book last night and was going to hack some code today, got the same problem.
I can confirm that rolling back to v1.0.0 solved the issue. Thx @mmonge 👍

**Comment by mmonge** [comment]
Hello Wim, I tried to test the modification in the `pom.xml`, but I just made a mess with the GitHub Actions in my repo.

In the end, I decided that I was doing the hard way just to have the brew installation. I just ran the native build on my Macbook and used the generated binary.

@merikan you can also create your native build if you want to, so you can have the latest version. Download the `ttcli` source code from GitHub and build it.

``` bash
sdk install java 21.0.1-graal
sdk use java 21.0.1-graal
mvn verify
mvn -Pnative native:compile

# check the generated file
ls -l target/ttcl
```
